import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 50,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
    backgroundColor: '#F8F9FA',
  },
  urlContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  urlText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#000000',
    marginLeft: 6,
  },
  content: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 40,
  },
  logoContainer: {
    alignItems: 'center',
    marginBottom: 24,
  },
  logoBox: {
    width: 60,
    height: 60,
    backgroundColor: '#1E62D0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  title: {
    fontSize: 24,
    fontWeight: '500',
    color: '#000000',
    marginBottom: 16,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 14,
    color: '#333333',
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 32,
    paddingHorizontal: 10,
  },
  boldText: {
    fontWeight: 'bold',
  },
  socialButton: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    height: 48,
    borderWidth: 1,
    borderColor: '#D0D0D0',
    borderRadius: 4,
    marginBottom: 12,
    paddingHorizontal: 16,
  },
  socialIconContainer: {
    width: 30,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  googleIcon: {
    width: 20,
    height: 20,
    resizeMode: 'contain',
  },
  socialText: {
    fontSize: 15,
    color: '#333333',
    fontWeight: '500',
    marginLeft: 8,
  },
  noteText: {
    fontSize: 13,
    color: '#757575',
    lineHeight: 18,
    marginTop: 4,
    marginBottom: 16,
  },
  dividerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    marginVertical: 16,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#E0E0E0',
  },
  dividerText: {
    marginHorizontal: 16,
    color: '#757575',
    fontSize: 12,
    fontWeight: '600',
  },
  inputWrapper: {
    width: '100%',
    position: 'relative',
    marginBottom: 24,
  },
  inputLabel: {
    position: 'absolute',
    top: -8,
    left: 12,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 4,
    zIndex: 1,
    fontSize: 12,
    color: '#555555',
  },
  input: {
    width: '100%',
    height: 52,
    borderWidth: 1,
    borderColor: '#D0D0D0',
    borderRadius: 4,
    paddingHorizontal: 16,
    fontSize: 16,
    color: '#000000',
  },
  continueButton: {
    width: '100%',
    height: 48,
    backgroundColor: '#1A62C6',
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 24,
  },
  continueButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  footerContainer: {
    alignItems: 'flex-start',
    width: '100%',
  },
  footerText: {
    fontSize: 14,
    color: '#333333',
  },
  footerLink: {
    color: '#1A62C6',
    fontWeight: '500',
  },
  bottomWebBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderTopWidth: 1,
    borderTopColor: '#E0E0E0',
    backgroundColor: '#F8F9FA',
  },
  bottomWebRightGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 24,
  },
});