import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 50,
    paddingBottom: 12,
    backgroundColor: '#000',
  },
  closeBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#A8C7FA',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  urlText: {
    fontSize: 15,
    color: '#A8C7FA',
  },
  content: {
    flexGrow: 1,
    paddingHorizontal: 32,
    paddingTop: 48,
    paddingBottom: 40,
  },
  logoWrap: {
    alignItems: 'center',
    marginBottom: 16,
  },
  logo: {
    width: 64,
    height: 64,
    borderRadius: 14,
    backgroundColor: '#1A62C6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  title: {
    fontSize: 26,
    fontWeight: '400',
    color: '#000',
    textAlign: 'center',
    marginBottom: 12,
  },
  subtitle: {
    fontSize: 14,
    color: '#444',
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 36,
  },
  socialBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 52,
    borderWidth: 1,
    borderColor: '#CDCDCD',
    borderRadius: 6,
    paddingHorizontal: 18,
    marginBottom: 12,
  },
  socialIcon: {
    width: 32,
    justifyContent: 'center',
  },
  socialLabel: {
    fontSize: 16,
    color: '#222',
    fontWeight: '500',
    marginLeft: 8,
  },
  gIcon: {
    width: 22,
    height: 22,
    resizeMode: 'contain',
  },
  note: {
    fontSize: 13,
    color: '#666',
    lineHeight: 18,
    marginTop: 6,
    marginBottom: 20,
  },
  divider: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 20,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#DCDCDC',
  },
  dividerText: {
    marginHorizontal: 16,
    color: '#888',
    fontSize: 13,
    fontWeight: '500',
  },
  inputWrap: {
    borderWidth: 1,
    borderColor: '#CDCDCD',
    borderRadius: 6,
    marginBottom: 28,
  },
  input: {
    height: 54,
    paddingHorizontal: 16,
    fontSize: 16,
    color: '#000',
  },
  continueBtn: {
    height: 52,
    backgroundColor: '#1A62C6',
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 28,
  },
  continueTxt: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  footer: {
    fontSize: 14,
    color: '#333',
  },
  footerLink: {
    color: '#1A62C6',
    fontWeight: '500',
  },
});